const step1 = () => {
    return new Promise( (resolve, reject) => {
        setTimeout( () => {
            console.log('Step 1 completed...');
            console.log('‚è≥');
            resolve();
        }, 2000);
    });
};


const step2 = () => {
    return new Promise( (resolve, reject) => {
        setTimeout( () => {
            console.log('Step 2 completed....');
            console.log('‚è≥');
            resolve();
        }, 2000);
    });
};


const step3 = () => {
    return new Promise( (resolve, reject) => {
        setTimeout( () => {
            console.log('Step 3 completed! The operation is done! üéâ Huzzah!!!');
            resolve();
        }, 2000);
    });
};



//Chaining Promises
step1().then(step2).then(step3).then( () => {
    console.log('üéä REQUEST COMPLETE. ü•≥')
    }
    ).catch( (error) => {
        console.log('‚òπÔ∏è ‚òπÔ∏è ‚òπÔ∏è ‚òπÔ∏è An error occured:', error)
});

